FIX: 'discourse watch all' cmd posting topics of categories which are private
discourse/discourse-slack-official pull request #29
Opened 2017-04-05 14:40 UTC by vinothkannans

'/discourse watch all' command posting topics of categories which are private

https://meta.discourse.org/t/slack-official-plugin-sending-topics-from-staff-categories/49578

2017-04-05 15:34 UTC, mcwumbly commented
I'm not familiar enough with the code these days to review this without
testing it.

Is it possible to add a test that fails before this fix to demonstrate this
fixes the issue?

On Apr 5, 2017 7:40 AM, "Vinoth Kannan" <notifications@github.com> wrote:

> '/discourse watch all' command posting topics of categories which are
> private
>
> https://meta.discourse.org/t/slack-official-plugin-sending-
> topics-from-staff-categories/49578
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/discourse/discourse-slack-official/pull/29
> Commit Summary
>
>    - FIX: 'discourse watch all' cmd posting topics of categories which
>    are private
>
> File Changes
>
>    - *M* plugin.rb
>    <https://github.com/discourse/discourse-slack-official/pull/29/files#diff-0>
>    (2)
>
> Patch Links:
>
>    - https://github.com/discourse/discourse-slack-official/pull/29.patch
>    - https://github.com/discourse/discourse-slack-official/pull/29.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/discourse/discourse-slack-official/pull/29>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ACHWtF8arM4ILBU4j0BJ1fdgZ9scnouLks5rs6fhgaJpZM4M0V9C>
> .
>

2017-04-06 01:55 UTC, tgxworld commented on plugin.rb
> +    if SiteSetting.slack_enabled? && DiscourseSlack::Slack.guardian.can_see?(post)
I'll move the logic into 

https://github.com/discourse/discourse-slack-official/blob/97ceba2ebda7f608ea9d6e9c8d83451ffc431589/lib/discourse_slack/slack.rb#L156-L157

2017-04-07 12:35 UTC, vinothkannans commented
@mcwumbly I will do once the logic moved to above mentioned place.

2017-04-10 08:59 UTC, tgxworld commented
Can we add a test case as well?

2017-04-11 12:52 UTC, vinothkannans commented
Sure. I will do @tgxworld  :+1:

2017-04-12 01:38 UTC, tgxworld requested changes

2017-04-12 01:38 UTC, tgxworld commented on spec/jobs/notify_slack_spec.rb
> +      Guardian.any_instance.expects(:can_see?).with(post).returns(false)
Let's not use a stub here. I prefer to just use an actual user object to test it. Stubs are fragile and isn't testing the underlying code properly.

2017-04-12 01:39 UTC, tgxworld commented
@vinothkannans Changes look good to me aside from a minor comment. Please squash your commits as well. :+1:

2017-04-12 12:47 UTC, vinothkannans commented
it's done. now it can be merged

2017-04-12 12:48 UTC, tgxworld commented on spec/jobs/notify_slack_spec.rb
> +      category.save!
Just a note, in the future you can just use `category.update!(read_restricted: false)`

2017-04-12 12:48 UTC, merged

2017-04-12 12:48 UTC, tgxworld commented
Thank you @vinothkannans :+1: