FIX: tags are missing in slack command status
discourse/discourse-slack-official pull request #32
Opened 2017-04-09 07:01 UTC by vinothkannans

related to this topic https://meta.discourse.org/t/discourse-status-slack-command-does-not-show-tags/60651?u=vinothkannans

2017-04-10 09:09 UTC, tgxworld requested changes

2017-04-10 09:09 UTC, tgxworld commented on lib/discourse_slack/slack.rb
> +          tag_list = row['tags'].present? ? "with tags *" + row['tags'].join(', ') + "*" : ""
`with_tags` needs to be translated.

2017-04-10 09:09 UTC, tgxworld commented on lib/discourse_slack/slack.rb
> +          tag_list = row['tags'].present? ? "with tags *" + row['tags'].join(', ') + "*" : ""
Also, the tags should not show when the tagging is disabled.

2017-04-10 09:09 UTC, tgxworld commented on lib/discourse_slack/slack.rb
> +        tag_list = row['tags'].present? ? "with tags *" + row['tags'].join(', ') + "*" : ""
We've duplicated logic in two places. While we're at it, can we see if we can refactor the code so that we don't duplicate logic?

2017-04-11 12:53 UTC, vinothkannans commented on lib/discourse_slack/slack.rb
> +        tag_list = row['tags'].present? ? "with tags *" + row['tags'].join(', ') + "*" : ""
sure :+1:

2017-04-11 12:54 UTC, vinothkannans commented on lib/discourse_slack/slack.rb
> +          tag_list = row['tags'].present? ? "with tags *" + row['tags'].join(', ') + "*" : ""
yeah. you are right :+1:

2017-04-11 13:20 UTC, tgxworld commented
Also tests please 😁

2017-04-12 01:41 UTC, tgxworld commented on lib/discourse_slack/slack.rb
> +      return "" unless if SiteSetting.tagging_enabled? && names.present?
`unless if`? :smile_cat:

2017-04-12 06:17 UTC, vinothkannans commented on lib/discourse_slack/slack.rb
> +      return "" unless if SiteSetting.tagging_enabled? && names.present?
:grin: I already found that typo in local and fixed. Will update it soon with tests :+1:

2017-04-12 08:01 UTC, vinothkannans commented
@tgxworld changes are done. Now it can be merged.

2017-04-12 08:14 UTC, tgxworld requested changes

2017-04-12 08:14 UTC, tgxworld commented on spec/integration/discourse_slack/slack_spec.rb
> +            list: "uncategorized, " + category.slug
This is very hard to read. Ideally, you'll want to format text like

```
text = <<~TEXT
#{I18n.t(...)}

#{category.slug}
TEXT
```

2017-04-12 08:21 UTC, tgxworld commented on spec/integration/discourse_slack/slack_spec.rb
> +            list: "uncategorized"
"uncategorized" is a hard coded string here. The test will break if the uncategorized category is renamed.

2017-04-12 11:45 UTC, vinothkannans commented
@tgxworld changes are done now

2017-04-12 12:44 UTC, tgxworld commented on spec/integration/discourse_slack/slack_spec.rb
> +            list: "uncategorized"
@vinothkannans  This hasn't been resolved.

2017-04-12 12:47 UTC, tgxworld requested changes

2017-04-12 12:47 UTC, tgxworld commented on spec/integration/discourse_slack/slack_spec.rb
> +                    channel: "#welcome",
Style: The indentation is really weird here. It is indented 3 spaces from `I18n` in the line above while the other addition in the code uses 2 spaces. Anyway, I prefer to just indent two spaces from the line above. Indenting more doesn't help with code readability at all and is just extra effort.

2017-04-12 13:07 UTC, vinothkannans commented
Now it's fixed. Should I squash my commits here too?

2017-04-12 13:14 UTC, tgxworld commented
@vinothkannans Yup you almost always want to squash your commits. "update" commits should really just be part of the main commit :)

2017-04-12 13:20 UTC, vinothkannans commented
@tgxworld it is now squashed :+1:

2017-04-12 13:37 UTC, tgxworld commented
Cool I'll test it out tml before merging.

2017-04-16 09:45 UTC, vinothkannans commented
@tgxworld I added two more commits which related to https://meta.discourse.org/t/discourse-status-should-only-show-the-status-for-the-current-channel/60892

If you are OK with these commits then I will squash it.

2017-04-18 08:10 UTC, tgxworld commented
Merged in https://github.com/discourse/discourse-slack-official/commit/1a32095d756d214ea465e0f890014a2049c04091. 

Thank you @vinothkannans

2017-04-18 08:10 UTC, closed without merging